name: howdays-docker

services:
  db:
    container_name: db
    image: postgres:17
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-data:

networks:
  backend:
    driver: bridge
